"""Income API: S3 model by default; MODEL_SOURCE=local for local checks."""

from contextlib import asynccontextmanager
import math
import os
from pathlib import Path

import boto3
from fastapi import FastAPI, HTTPException, Request
import joblib
import pandas as pd
from pydantic import BaseModel

MODEL_KEY = "artifacts/current/model.joblib"


def download_model() -> Path:
    """Download the approved model using the AWS credential chain/EC2 role."""
    bucket_name = os.environ.get("ARTIFACT_BUCKET")
    if not bucket_name:
        raise RuntimeError("Set ARTIFACT_BUCKET before starting the cloud API.")
    path = Path(os.environ.get("MODEL_PATH", "~/models/model.joblib")).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_suffix(".download")
    s3 = boto3.client("s3")
    s3.download_file(bucket_name, MODEL_KEY, str(temporary_path))
    temporary_path.replace(path)
    print(f"Downloaded model from s3://{bucket_name}/{MODEL_KEY}")
    return path


@asynccontextmanager
async def lifespan(app: FastAPI):
    source = os.environ.get("MODEL_SOURCE", "cloud")
    if source == "local":
        model_path = Path(os.environ.get("MODEL_PATH", "models/model.joblib")).expanduser()
    elif source == "cloud":
        model_path = download_model()
    else:
        raise RuntimeError("MODEL_SOURCE must be 'cloud' or 'local'.")
    app.state.model = joblib.load(model_path)
    yield
    app.state.model = None


app = FastAPI(title="Adult Income API", lifespan=lifespan)


class ScoreRequest(BaseModel):
    features: list[float]


@app.get("/healthz")
def healthz(request: Request):
    if getattr(request.app.state, "model", None) is None:
        raise HTTPException(status_code=503, detail="Model is not ready")
    return {"status": "ok"}


@app.post("/score")
def score(req: ScoreRequest, request: Request):
    """Input order is the same as the ten columns generated by prepare_data.py."""
    if len(req.features) != 10:
        raise HTTPException(status_code=400, detail="Expected 10 features (adult income)")
    if not all(math.isfinite(value) for value in req.features):
        raise HTTPException(status_code=400, detail="Features must be finite numbers")
    model = getattr(request.app.state, "model", None)
    if model is None:
        raise HTTPException(status_code=503, detail="Model is not ready")
    frame = pd.DataFrame([req.features], columns=model.feature_names_in_)
    prediction = int(model.predict(frame)[0])
    return {
        "prediction": prediction,
        "label": "thu_nhap_cao" if prediction == 1 else "thu_nhap_thap",
    }


def main():
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)


if __name__ == "__main__":
    main()
